title: Dogs of Harrison Park
description: Dogs of Harrison Park Calendar

url: http://camerond17.github.com/dogs-of-harrison-park
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Upload - GO HERE!
    url: /upload
  - title: Sponsors
    url: /sponsors
  - title: FAQ
    url: /faq
  - title: Contact
    url: /contact

social:
  github: camerond17/dogs-of-harrison-park
  facebook: DogCalendar2021
  email: dogsofharrisonpark@gmail.com

google_analytics: "UA-176405143-1"
